FROM python:3.10-slim

RUN apt-get update
RUN apt-get install -y git

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# comment below out after initial dev effort
COPY requirements-test.txt .
RUN pip install --no-cache-dir -r requirements-test.txt

# COPY app.py .
COPY ./* .

# Expose the port the app runs on
EXPOSE 8000

# productionize the below command after initial dev effort
CMD ["flask", "--app", "app.py", "--debug", "run", "--host", "0.0.0.0","--port", "8000"]
